### ISSUE TITLE
Problem with infinite carry 2.13

### ISSUE THREAD

**Issue by fullbanner** [FINDarkside/TLD-Save-Editor#1]
Infinite carry in the player tab, does not read or write the value from/to the save game.
It is working fine in 2.12.

**Comment by FINDarkside** [comment]
Thanks for the report. I have fixed this now, and I'll release 2.13.1 soon!

**Comment by FINDarkside** [comment]
2.13.1 released on [ModDB](https://www.moddb.com/mods/the-long-dark-save-editor-2/downloads/tld-save-editor-213-v144) and [here](https://github.com/FINDarkside/TLD-Save-Editor/releases/tag/2.13.1). Thanks for the report!
