### ISSUE TITLE
UnKnown LakeCabin Keys

### ISSUE THREAD

**Issue by febitanya** [FINDarkside/TLD-Save-Editor#13]
GEAR_LakeCabinKey1
GEAR_LakeCabinKey2
GEAR_LakeCabinKey3

can you add pls

**Comment by FINDarkside** [comment]
I know this is old issue, but if you or someone can save me a save where these items area needed for something I'll add these. At the moment it's pretty hard to test whether it works correctly.

**Comment by Pt-Djefferson** [comment]
Done.
