### ISSUE TITLE
editing location results in error (falling in void)

### ISSUE THREAD

**Issue by agrunwald82** [FINDarkside/TLD-Save-Editor#14]
I was able to open saves and edit my character and inventory (thank you!) but twice now have tried to teleport via the map marker only to open the game and be in a white void of nothingness, probably falling as my fatigue was going down double-time. I couldn't see anything but whiteness.

I was in TWM, outside, teleporting (moving the map marker) elsewhere in TWM. 

This is likely the same "void fall" error experienced previously when moving the map marker from an indoor location.

**Comment by FINDarkside** [comment]
The game doesn't teleport player to the ground on game load. I have disabled the editor automatically modifying your z coordinate to very high value and added z coordinate field. From now on, you need to manually set your z coordinate.
