### ISSUE TITLE
Adding rifle ammo deletes the hunter rifle from the save file

### ISSUE THREAD

**Issue by ASmellie** [FINDarkside/TLD-Save-Editor#16]
Save editor version 2.14.2

With a hunter rifle in your inventory, open the save editor and add more rifle ammo
Save the file

When opened in the game, the hunter rifle has disappeared from the inventory

I don't have chapter 3 installed

**Comment by Pt-Djefferson** [comment]
I`ll check it.

**Comment by Pt-Djefferson** [comment]
Save editor 2.15.0, TLD 1.16 55716. Everything fine. Rifle does not disappear.

**Comment by FINDarkside** [comment]
@ASmellie Let me know if you can still reproduce this. If not, I'll close this issue.
