### ISSUE TITLE
Version 2.14.2 save-corruption fix (may be)

### ISSUE THREAD

**Issue by Pt-Djefferson** [FINDarkside/TLD-Save-Editor#17]
Change m_Timestamp variable type from DateTime to string.
GlobalData.cs => public string m_Timestamp { get; set; }
and
GameSave.cs => SlotData.m_Timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

The savegame remains a mess, but loadable mess (story and survive).

**Comment by FINDarkside** [comment]
Thank you!

If you want, you can create issues about the other stuff that's messed up. I'm not sure I'll keep maintaining this since the switch to IL2CPP made maintaining this a lot more tedious, but it never hurts to have documented issues.

**Comment by Pt-Djefferson** [comment]
OK. Glad to help.
Have some data structure changes but need to do dome tests.

**Comment by FINDarkside** [comment]
To simplify things, most of the fields could be removed from the data classes . DynamicSerializable will take care that data isn't lost even if fields are missing from [GlobalData](https://github.com/FINDarkside/TLD-Save-Editor/blob/master/The%20Long%20Dark%20Save%20Editor%202/Game%20data/GlobalData.cs). Most of the fields aren't used, but they are leftovers from the time I had the whole save format defined there.
