### ISSUE TITLE
Refresh button does not refresh profile

### ISSUE THREAD

**Issue by navoznov** [FINDarkside/TLD-Save-Editor#2]
Steps to reproduce:
1) make a backup of the save file 
2) open the save file in TLD-Save-Editror
3) change the BookSmartProgress slider value
4) press the "save" button
5) restore the save file from the backup
6) press the "refresh" button on the dialog form
7) profit! The BookSmartProgress  slider value was not restored.

**Comment by FINDarkside** [comment]
Thanks for the report. It seems like profile file is not refreshed at all, so nothing in Profile tab will be refreshed. I'll fix this when I have time.
