### ISSUE TITLE
Double editor loading speed

### ISSUE THREAD

**Issue by Pt-Djefferson** [FINDarkside/TLD-Save-Editor#20]
Just comment out UpdateSaves(); in TestBranch set method.
There is another one called in Window_Loaded() method.

**Comment by FINDarkside** [comment]
There used to be toggle for toggling between test branch, and I might enable it again so that's why it needs to update saves when testBranch is changed. But I think I we can remove UpdateSaves from Winwow_Loaded. Good catch, thanks! Fixed with 1f73e4c6f85022636d421fdddebf3cb068853101
