### ISSUE TITLE
There are updated maps that you can use in the editor

### ISSUE THREAD

**Issue by thinkpad4** [FINDarkside/TLD-Save-Editor#49]
@FINDarkside Hi, on the Steam Community page for the Long Dark user  stmSantana updated the maps that Whiteberry, Stray Wolf made with the new things added in the latest updates.  https://steamcommunity.com/sharedfiles/filedetails/?id=1901570789

**Comment by FINDarkside** [comment]
Thanks, might update at some point but I'm pretty busy at the moment.
