### ISSUE TITLE
Can this be updated to 1.76 please?

### ISSUE THREAD

**Issue by thinkpad4** [FINDarkside/TLD-Save-Editor#52]
@FINDarkside can you please update this to work with all the new additions in 1.76?  Thank you very much

**Comment by Pt-Djefferson** [comment]
fixed

**Comment by thinkpad4** [comment]
@FINDarkside YAY!  Can't wait for it to be released.  Thank you

**Comment by FINDarkside** [comment]
[2.17 released](https://www.moddb.com/mods/the-long-dark-save-editor-2/downloads/tld-save-editor-217-v176). Thanks @Pt-Djefferson!
