### ISSUE TITLE
Use on Linux Version?

### ISSUE THREAD

**Issue by antrys** [FINDarkside/TLD-Save-Editor#66]
Does this compile on Linux?
Doesn't seem to run on Wine, I can't click on OK on the "don't bug hinterland" startup popup.
If so, of if no, can you change where it looks for save files?  Maybe I can run it in a Windows VM and point to a share?

**Comment by FINDarkside** [comment]
WPF doesn't work on Linux so no. Not sure if it's possible to get it to work with wine. Having option to manually change the location of save files would be a good feature, but I'm not actively developing this anymore. If someone wants to make pr for it, I'll merge though.
