### ISSUE TITLE
TLD is updated

### ISSUE THREAD

**Issue by RafaelNET** [FINDarkside/TLD-Save-Editor#81]
Is showing only old saves, could you repair this app? tnx

**Comment by FINDarkside** [comment]
I won't maintain this anymore as it takes too much time and it's just not interesting anymore. Originally I started with this project in 2015 so there's also lots of technical debt.

I've experimented with new version here: https://github.com/FINDarkside/TLD-Save-Editor-3 (won't work with latest update)
But that was before the last update, I haven't taken a look how extensive the save format changes are so I haven't decided if I'll continue with that or not.

**Comment by DragonWest** [comment]
Oh thats some bad news :(  
It was an awesome editor mod, like its the best mod for The long dark because you basically can do anything with it! 

Now its gone :/ 
Thank you so much for your amazing work! 
Rip TLD editor Dec 2022

**Comment by leewbl** [comment]
its good. I first think of this save editer when the game updated, best regards.

**Comment by leewbl** [comment]
> I won't maintain this anymore as it takes too much time and it's just not interesting anymore. Originally I started with this project in 2015 so there's also lots of technical debt.
> 
> I've experimented with new version here: https://github.com/FINDarkside/TLD-Save-Editor-3 (won't work with latest update) But that was before the last update, I haven't taken a look how extensive the save format changes are so I haven't decided if I'll continue with that or not.

its good. I first think of this save editer when the game updated, best regards.

**Comment by rafael-newtech** [comment]
> > I won't maintain this anymore as it takes too much time and it's just not interesting anymore. Originally I started with this project in 2015 so there's also lots of technical debt.
> > I've experimented with new version here: https://github.com/FINDarkside/TLD-Save-Editor-3 (won't work with latest update) But that was before the last update, I haven't taken a look how extensive the save format changes are so I haven't decided if I'll continue with that or not.
> 
> its good. I first think of this save editer when the game updated, best regards.

The same with me

**Comment by baudamir** [comment]
Я очень надеюсь, что когда-нибудь будет обновление!

**Comment by FINDarkside** [comment]
It should work now, apart from story mode saves. Fixed by #83
