### ISSUE TITLE
How to "Permanently: 0 Weight, 100 Conditions and Invulnerable?"

### ISSUE THREAD

**Issue by MiddlEarth777** [FINDarkside/TLD-Save-Editor#82]
Hi
I know you won't bother with this editor anymore.
What I'm wondering is:
How can I permanently(so even if i exit the game and re-enter) set 0 weight, 100 conditions and invulnerability in the saved game?

**Comment by FINDarkside** [comment]
I don't think it's possible.

**Comment by MiddlEarth777** [comment]
hmm actually the save editor version 2.18 was working fine when we removed some objects from the inventory, wouldn't it be possible to just update it with a few minor tweaks to make it compatible with the new version instead of completely rewriting it?

**Comment by FINDarkside** [comment]
I don't know

**Comment by MiddlEarth777** [comment]
Okey Fin, thank you, good luck
